### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by chew-z** [HyShai/youtube-dl#2]
On anything else beside your example video

try this https://m.youtube.com/watch?v=-CmadmM5cOk

Signature extraction failed: Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/Documents/site-packages/youtube_dl/extractor/youtube.py", line 634, in _decrypt_signature
    video_id, player_url, s
  File "/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/Documents/site-packages/youtube_dl/extractor/youtube.py", line 548, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/Documents/site-packages/youtube_dl/extractor/youtube.py", line 612, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/Documents/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gG'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output

**Comment by HyShai** [comment]
If you have trouble with a specific video, try to use the non-mobile url (e.g. http://youtu.be/-CmadmM5cOk or https://www.youtube.com/watch?v=-CmadmM5cOk )

See also https://github.com/rg3/youtube-dl/issues/2858

**Comment by chew-z** [comment]
Alternative urls throws exceptions as well. Just as other popular videos on youtube.

I am just pointing out that this code isn't working or throws exceptions for several, popular youtube videos. So I wonder if you have tested it a bit  before 'commit'. This is github not facebook.

As for 'mobile url' - you are attempting to make a fork for Pythonista which seems to be a mobile app.

Sure, going through the code and making a working fork myself won't be that difficult.

[0;33mWARNING:[0m Writing cache to u'/private/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/.cache/youtube-dl/youtube-sigfuncs/js_en_US-vflT9SJ6t_40.43.json' failed: Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/Documents/site-packages/youtube_dl/cache.py", line 46, in store
    os.makedirs(os.path.dirname(fn))
  File "/private/var/mobile/Containers/Bundle/Application/0F009021-6E5A-4727-A692-5E7231941A67/Pythonista.app/pylib/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/private/var/mobile/Containers/Bundle/Application/0F009021-6E5A-4727-A692-5E7231941A67/Pythonista.app/pylib/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/private/var/mobile/Containers/Bundle/Application/0F009021-6E5A-4727-A692-5E7231941A67/Pythonista.app/pylib/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/3A8E99FD-AFD6-4DEA-9BDB-7B34E8C8626B/.cache'

**Comment by HyShai** [comment]
The video that you posted has been tested (and works using the alternate urls), as has many other videos. If there's a specific bug that seems related specifically to this fork please post it here. Otherwise this seems like an issue related to the upstream branch.  

In general, the youtube-dl library is very flimsy because much of it relies on screen scraping. I apologize that I haven't updated this as frequently as I would like and is needed. As an alternative, you can try the [youtubedl-downloader](https://github.com/shaun-h/pythonista-youtubedl-downloader) script by @shaun-h


The scripts that were provided in the README were only examples - you can trivially add a mobile url "converter" to your own script.
